### ISSUE TITLE
ambiguous versions of binObs_py.F

### ISSUE THREAD

**Issue by adarmenov** [GEOS-ESM/AeroApps#7]
Two versions of binObs_py.F are in the source tree:
    1. ./src/Components/misc/scat/binObs_py.F
    2. ./src/Shared/GMAO_Shared/GMAO_pyobs/binObs_py.F

This could result in unintended behavior depending on how code is compiled/linked.

**Comment by patricia-nasa** [comment]
Anton - I changed the naming in scat to be unambiguous
